### ISSUE TITLE
All authentication must be done over SSL

### ISSUE THREAD

**Issue by manishprajapatidev** [andmar8/Panopto-PHP-Client#3]
On every call of any function it return a catch with this message. even if I run on https server but it remain same. any help?

```
$SMClient = new SessionManagementClient($server, $auth);
   try
   { 
    $SMClient->addFolder("Octal"); 
   }
   catch(Exception $e)
   {
    echo "ERROR: ".$e->getMessage();
   }
```

**Comment by andmar8** [comment]
This code base is not maintained, please try https://github.com/lucisgit/php-panopto-api instead

If you really want to use this version, try var_dump-ing the $e variable in the catch block to see more verbose error details
